### ISSUE TITLE
update libsodium library

### ISSUE THREAD

**Issue by sean-codevasp** [terl/lazysodium-java#134]
Seems like lazy sodium is using 1.0.18.
Now, there is new version 1.0.19.

You might want to update the bundled library.
 
https://github.com/jedisct1/libsodium/releases

**Comment by sean-codevasp** [comment]
Now its 1.0.20 https://github.com/jedisct1/libsodium/releases

**Comment by zabicki-iterable** [comment]
@sean-codevasp Are you sure it's updated? I don't see any files in the repo having been updated more recently than 2 years ago.

Also 5.1.4 is the latest at https://github.com/terl/lazysodium-java/releases. And maven doesn't https://mvnrepository.com/artifact/com.goterl/lazysodium-java

And I don't see see any of the aegis methods available, and those seem to have been added in libsodium 1.0.19.

**Comment by sean-codevasp** [comment]
@zabicki-iterable yes. lazy sodium is not updated. however, libsodium original library has been updated.
