### ISSUE TITLE
Expose buffer sizes for native interfaces

### ISSUE THREAD

**Issue by keeferrourke** [terl/lazysodium-java#17]
Hey there! LazySodium looks like it's shaping up to be probably the best Libsodium Java binding library, but it doesn't expose `libsodium`'s [pre-calculated authenticated encryption](https://download.libsodium.org/doc/public-key_cryptography/authenticated_encryption.html#precalculation-interface) interface properly.

In particular, in the Box interface, the value of `BEFORENMBYTES` etc is not publicly accessible. The code I'm writing needs to fill a shared secret `k` using the `LazySodium.cryptoBoxEasyBeforeNm()` method, but I had to dig around to figure out that the buffer size should be 32 bytes long.

I'm doing something like
```java
        byte[] sharedSecret = new byte[32];
        if (!sodium.cryptoBoxBeforeNm(sharedSecret, bobsPubKey, alicesSecKey)) {
            return false;
        };
```
But it would be much more clear if I could do something like:
```java
        byte[] sharedSecret = new byte[LazySodium.BEFORENMBYTES];
```

Could this buffer size (and others) be exposed publicly?

**Comment by gurpreet-** [comment]
Hello!

Glad you're enjoying Lazysodium! 🙌 

It seems I missed all those pre-calculated functions out (whoops!). Of course I can add them for you and expose those sizes publicly. Give me a sec and I'll add some Lazy functions in too.

**Comment by keeferrourke** [comment]
@gurpreet- much appreciated, thanks! :smile:

**Comment by gurpreet-** [comment]
Hello again.

I just checked and it seems I did add those sizes into the `Box` interface.

```java
// The byte sizes are available in their relevant interfaces like so...
byte[] sharedSecret = new byte[Box.BEFORENMBYTES];
```

You can find similar array sizes at the start of their respective interfaces. For example the `KeyExchange` interface has these byte sizes available for you:

```java
public interface KeyExchange {

    int PUBLICKEYBYTES = 32;
    int SECRETKEYBYTES = 32;
    int SESSIONKEYBYTES = 32;
    int SEEDBYTES = 32;
    String PRIMITIVE = "x25519blake2b";

    // ... rest of interface
}
```

I've made a note to make that clearer in the documentation 👍

**Comment by keeferrourke** [comment]
@gurpreet- whoops, my bad. Thanks a bunch!

**Comment by gurpreet-** [comment]
No worries @keeferrourke.

I've added lazier functions for the precalculation interface a.k.a [`Box.java`](https://github.com/terl/lazysodium-java/blob/bf44294d68bb231856c4c8723e790ddd82892060/src/main/java/com/goterl/lazycode/lazysodium/interfaces/Box.java) (and fixed a minor typo in one of the functions). It's now available as release `1.1.1` on [Bintray](https://bintray.com/terl/lazysodium-maven/lazysodium-java/1.1.1) and [GitHub](https://github.com/terl/lazysodium-java/releases/tag/1.1.1).

If you have any more problems/questions, please let me know.

Until then, have fun! 🎆

**Comment by gurpreet-** [comment]
Hey @keeferrourke,

If Lazysodium has helped you please consider donating. Even a dollar goes a long way.

<a href="https://www.patreon.com/terlacious"><img src="https://filedn.com/lssh2fV92SE8dRT5CWJvvSy/patron_button.png" width="140" /></a>

Thanks for using Lazysodium :)

**Comment by keeferrourke** [comment]
Hey @gurpreet- are you folks on [Liberapay](https://liberapay.com/)? I'd be happy throw a couple dollars your way, since this library is being developed so quickly and with extremely high quality. My usage is more one-off (but maybe I'd use it more in the future), but you saved me from having to write bindings myself :wink:

**Comment by gurpreet-** [comment]
Hey @keeferrourke. 

Thanks for the compliments! I got tired of using low quality libs a while ago 😪. I think I'm going to expand Lazysodium to the languages that run iOS, Mac and Windows so then devs can use it to build high quality cryptography applications. I personally would like to see a GPG rival but with a better interface so everyone can use it 😄 

One off donations are totally fine too! Just created a Liberapay account https://liberapay.com/terlacious/ 

Thanks so much!
