### ISSUE TITLE
Documentation plan

### ISSUE THREAD

**Issue by gurpreet-** [terl/lazysodium-java#18]
Many parts of the docs still need completing, such as the collaborator's guide and how to add native functions. I think the best plan of action is to centralise the documentation into one place.

**Plan of action**:
- [x] Buy lazycode.co.
- [x] Setup GitBooks.
- [x] Transfer documentation.

**Comment by gurpreet-** [comment]
New documentation available at:
* Lazysodium documentation: https://docs.lazycode.co/lazysodium 
* [GitHub link for editing and making PRs.](https://github.com/terl/lazysodium-docs)

Only need to transfer documentation now.

**Comment by gurpreet-** [comment]
Hello @schott12521.

If you have the compiled `libsodium.so` files in their relevant ABI folders in the `jniLibs` folder then I think those `libsodium.so` files will be added automatically to your path. So I think the solution to your problem is simply to omit the path altogether:

```kotlin
val sodium = SodiumAndroid()
val lazySodium = LazySodium(sodium, StandardCharsets.UTF_8)
```

Let me know if that works out for you. 

I will add this to the docs too.

**Comment by gurpreet-** [comment]
Or if that doesn't work then you could extend `SodiumAndroid` and then initialise it:

```kotlin
class MySodiumAndroid : SodiumAndroid { }

//  then ...
val sodium = SodiumAndroid()
val lazySodium = LazySodium(sodium, StandardCharsets.UTF_8)
```

**Comment by schott12521** [comment]
Correct, I think I got it to work just by assigning a new name to it. Not exactly sure what I am doing wrong now, the fork of libsodium that I use basically just changed the crypto_sign functions to use blake2b internally for hashing, but im not getting the expected hash when I use the LazySign method.

**Comment by gurpreet-** [comment]
Are you performing a `crypto_sign` then a `crypto_generichash_blake2b` or are you doing the hashing first and then the signing? 

 If you're getting a hash back, then it's a good sign that you're on the right tracks. It may be that you're not providing the correct lengths to `crypto_sign` or `crypto_generichash_blake2b`?

Could you show me some code? Any C and Java code that you've modified and added would be helpful.
