### ISSUE TITLE
​Ed25519 to Curve25519

### ISSUE THREAD

**Issue by PaulSeiziger** [terl/lazysodium-java#21]
Hello, when is it planned to introduce support for converting Ed25519 to Curve25519?

**Comment by gurpreet-** [comment]
Hello @PaulSeiziger,

Many thanks for the pull request #22.

I'll merge and add this right now for you.

**Comment by gurpreet-** [comment]
Added in the latest release [`2.1.0`](https://github.com/terl/lazysodium-java/releases/tag/2.1.0).

Thanks!

**Comment by gurpreet-** [comment]
Hey @PaulSeiziger,

If Lazysodium has helped you please consider donating. Even a dollar goes a long way.

<a href="https://www.patreon.com/terlacious"><img src="https://filedn.com/lssh2fV92SE8dRT5CWJvvSy/patron_button.png" width="140" /></a>

Thanks for using Lazysodium :)
