### ISSUE TITLE
Path error on Windows

### ISSUE THREAD

**Issue by intfrog** [terl/lazysodium-java#24]
Hi,
I tested on Windows but it failed to initialize. And below is what I found from the source code.
In Windows the path is like "\windows\libsodium.dll", so the check of `path.startsWith("/")` in `NativeUtils` will fail.

**Comment by gurpreet-** [comment]
Hello @intfrog. Yes, you're right it seems I misplaced that check.

Also there seems to be a misuse of `File.separator` on my part in the `getLibSodiumFromResources` method.

I'm working on this right now and I've got a fix. Sit tight and I'll release it soon 👍

**Comment by gurpreet-** [comment]
Hello, just released [`2.2.1`](https://bintray.com/terl/lazysodium-maven/lazysodium-java/2.2.1) with the fix included.

Let me know if it works for you 😄

**Comment by intfrog** [comment]
@gurpreet- Great! Now it works :)
