### ISSUE TITLE
Maven usage

### ISSUE THREAD

**Issue by rendaw** [terl/lazysodium-java#26]
Bintray is nonstandard and I found it fairly difficult to use compared to standard (maven central) releases where all I need is a dependency.  I had these issues:

1. Just adding a dependency doesn't work, you need to define a new maven repository.
2. The bintray "set me up" button says you need a settings.xml and need to create a profile, add repositories and pluginRepositories to it.  You don't - all you need is the repositories section and you can add it directly to pom.xml.
3. The dependency mustn't have `<type>pom</type>` - the dependency won't resolve if it's present.

TBH it might not have been difficult if the repository config was documented next to the dependency config.

**Comment by gurpreet-** [comment]
Hello!

Thanks for this. I've added a new [Installation page]()https://docs.lazycode.co/lazysodium/installation to the docs, which makes adding Lazysodium clearer. Hopefully this is an improvement!

**Comment by rendaw** [comment]
Yeah, looks great!
