### ISSUE TITLE
Request for HMAC :)

### ISSUE THREAD

**Issue by rendaw** [terl/lazysodium-java#27]
My use case is generating authentication tokens so a user's password doesn't have to be remembered in as many places.

I think this can be worked around by hashing + then using crypto_auth, but it's more steps and I think ends up repeating some operations.

No urgent need because of workaround, but :+1: for this feature.

**Comment by gurpreet-** [comment]
Hello again! I'll be working on this today!

Just created a [Patreon](https://www.patreon.com/terlacious) profile. If Lazysodium's been useful to you, please consider funding Terl's open-source efforts 👍

**Comment by gurpreet-** [comment]
Released in [`2.4.0`](https://github.com/terl/lazysodium-java/releases/tag/2.4.0).
