### ISSUE TITLE
Help us, Patreon and Liberapay

### ISSUE THREAD

**Issue by gurpreet-** [terl/lazysodium-java#28]
Open-source isn't particularly well-funded. 

Some of the most popular libraries often go unfunded and therefore are disbanded. I've created a [Patreon](https://www.patreon.com/terlacious) page and a [Liberapay](https://liberapay.com/terlacious/) page to make sure that Terl's present and future open-source projects remain well-maintained and open-source.

It'll help us to keep improving Lazysodium and **hopefully branch out to more languages** 🙌 

Thanks!

<a href="https://www.patreon.com/bePatron?u=11667122"><img src="https://filedn.com/lssh2fV92SE8dRT5CWJvvSy/patron_button.png" width="140" /></a>

<a href="https://liberapay.com/terlacious/"><img src="https://filedn.com/lssh2fV92SE8dRT5CWJvvSy/liberapay.png" width="68" /></a>

**Comment by MyGodIT** [comment]
![image](https://user-images.githubusercontent.com/29084833/43059376-b6aba4de-8e7e-11e8-907f-009a989af7ad.png)

![image](https://user-images.githubusercontent.com/29084833/43059354-a3b03098-8e7e-11e8-8dc2-69c99436588a.png)
How can i do for this
