### ISSUE TITLE
Additional Signing Key Support

### ISSUE THREAD

**Issue by m4dc4p** [terl/lazysodium-java#32]
Sometimes its useful to get a public key, given a Ed25519 private key (or to get the seed). Please add support for `crypto_sign_ed25519_sk_to_pk` and `crypto_sign_ed25519_sk_to_seed`.

**Comment by gurpreet-** [comment]
Hello again @m4dc4p 

Thanks for all these pull requests my dude! I've merged this one.

Anything else you need adding?

**Comment by m4dc4p** [comment]
That is it for now. Really appreciate your speed on merging these!

(I am enhancing [an SDK](https://github.com/tozny/e3db-java) that previously used Kalium (Plain) & libsodium-jni (Android). LazySodium is sooo much nicer to use!)

**Comment by gurpreet-** [comment]
Looks like a very sweet project. An end-to-end encrypted database that works seamlessly? I applaud you and your organisation's product.

Thanks for the compliments 🙌if you want to keep Lazysodium going, consider [becoming a supporter](https://www.patreon.com/terlacious) or a [sponsor](https://docs.lazycode.co/lazysodium/sponsors) as I'm planning to broaden Lazysodium into more languages and tools. 

Alternatively, keep the PRs coming 😃 👍

**Comment by gurpreet-** [comment]
Released in version [`2.5.0`](https://github.com/terl/lazysodium-java/releases/tag/2.5.0) 👍
