### ISSUE TITLE
 crypto_box_open_detached interface wrong

### ISSUE THREAD

**Issue by yishais** [terl/lazysodium-java#54]
In LazySodium, 
`public boolean cryptoBoxOpenDetached(byte[] message, byte[] cipherText, byte[] mac, byte[] cipherTextLen, byte[] nonce, byte[] publicKey, byte[] secretKey) 
`
seems to be wrong with defining   
`byte[] cipherTextLen `   instead of long. 
This goes all the way down in the interface, and eventually ends with a crash as byte[] in java is passed by reference, so converting a long to a byte[4] will not work.

**Comment by gurpreet-** [comment]
Hi @yishais,

Nice catch! I've fixed the problem on `master`. A formal release will be upcoming shortly with this change in.

Thank you for reporting.

**Comment by gurpreet-** [comment]
These changes are now incorporated in release `4.1.0`. Thank you so much for improving Lazysodium 😄
