### ISSUE TITLE
cryptoBoxEasyAfterNm pointer problem

### ISSUE THREAD

**Issue by Ogromny** [terl/lazysodium-java#59]
Hi,

When i run:
```kotlin
    fun encrypt(secretKey: Key, nonce: ByteArray, message: ByteArray): ByteArray {
        var cipherText = ByteArray(message.size)

        sodium.cryptoBoxEasyAfterNm(cipherText, message, message.size.toLong(), nonce, secretKey.asBytes)

        return cipherText
    }
```

I get:
> munmap_chunk(): invalid pointer

Is it me or it's a bug ? What can I do ?

Sorry for my basic English

**Comment by gurpreet-** [comment]
Hi @Ogromny,

Thank you for reporting this. Could you please answer a few questions while I investigate further:

1. What Java version are you using?
2. What Lazysodium version are you using?
3. What platform are you running this on?

**Comment by gurpreet-** [comment]
Oh I think I might have spotted something. The `cipher` length should be `messageBytesLength + Box.MACBYTES`. For example:

```java
byte[] cipher = new byte[messageBytes.length + Box.MACBYTES];
```
