### ISSUE TITLE
Signature mismatch for native method "crypto_generichash_blake2b_salt_personal()"

### ISSUE THREAD

**Issue by jcihocki** [terl/lazysodium-java#75]
Created a PR here, if you're interested: https://github.com/jcihocki/lazysodium-java/pull/

native method declared in Sodium.java has `subKeyId` as `long`, native method expects `unsigned char *`  for both `salt` and `personal` so it should be `byte[]`

**Comment by gurpreet-** [comment]
Hey nice spot, I have updated this and will be available in the next release!

**Comment by jcihocki** [comment]
Awesome, thank you!

**Comment by nathankurtyka** [comment]
@gurpreet- Hello! Any approximate timeline for the next release?

I only ask because we're considering migrating our production stack to LazySodium, and this issue might be a blocker.

**Comment by gurpreet-** [comment]
@nathankurtyka Will release a new version today! It contains a minor breaking change in order to fix some scrypt related methods.

**Comment by gurpreet-** [comment]
Fixed in release [4.3.0](https://github.com/terl/lazysodium-java/releases/tag/4.3.0).

**Comment by gurpreet-** [comment]
I've migrated my CI infrastructure to AzureCI so now we also have the benefit of testing across platforms rather than just testing on Linux. Should be extra resilient to these failures. 

Will update Lazysodium Android ASAP too.
