### ISSUE TITLE
Dependency to unstable SLF4J Version 2.0.0-alpha1

### ISSUE THREAD

**Issue by KlausCall** [terl/lazysodium-java#93]
Your dependency to SLF4J Version 2.0.0-alpha1 references an unstable/experimental version (with respect to http://www.slf4j.org/download.html )

It would be helpful to reduce the required version to the latest stable SLF4J version ( currently 1.7.30).
It looks like this is suffficient for your project. Additinal SLF4J seems to be supported from JDK9 while lazysodium laso targets JDK 8.

**Comment by lomigmegard** [comment]
I think this is very important and has been preventing me to upgrade since this change. 
A cryptographic library should not depend on an alpha dependency.
